services:
  cadastro-app:
    build: .
    container_name: cadastro-streamlit
    ports:
      - "8501:8501"
    volumes:
      # Volume para persistir os dados da aplicacao
      - ./data:/app/data
      # Volume para persistir arquivos de configuracao
      - ./config:/app/config
      # Volume para logs (opcional)
      - ./logs:/app/logs
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
    restart: unless-stopped
    networks:
      - cadastro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api-server:
    build: .
    container_name: cadastro-api
    ports:
      - "5000:5000"
    volumes:
      # Volume para persistir os dados da aplicacao
      - ./data:/app/data
      # Volume para persistir arquivos de configuracao
      - ./config:/app/config
      # Volume para logs (opcional)
      - ./logs:/app/logs
    environment:
      - FLASK_APP=api_server.py
      - FLASK_ENV=production
    command: ["python", "api_server.py"]
    restart: unless-stopped
    networks:
      - cadastro-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Servico opcional para nginx como proxy reverso (descomente se necessario)
  # nginx:
  #   image: nginx:alpine
  #   container_name: cadastro-nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - cadastro-app
  #   restart: unless-stopped
  #   networks:
  #     - cadastro-network

networks:
  cadastro-network:
    driver: bridge

volumes:
  cadastro-data:
    driver: local 