# Docker Compose para Cadastro Streamlit - Versao Simplificada
# Compativel com Docker Compose v1 e v2 (incluindo Raspberry Pi)

services:
  # Servico PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: cadastro_banco
    environment:
      - POSTGRES_DB=cadastro_db
      - POSTGRES_USER=cadastro_user
      - POSTGRES_PASSWORD=cadastro_password
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --lc-collate=C --lc-ctype=C
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
      - ./database/backups:/backups:rw
    restart: unless-stopped
    networks:
      - cadastro-network

  cadastro-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadastro_app
    ports:
      - "8503:8501"
    volumes:
      - ./data:/app/data:rw
      - ./config:/app/config:rw
      - ./logs:/app/logs:rw
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=cadastro_db
      - POSTGRES_USER=cadastro_user
      - POSTGRES_PASSWORD=cadastro_password
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped
    networks:
      - cadastro-network
    depends_on:
      - postgres

  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadastro_api
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data:rw
      - ./config:/app/config:rw
      - ./logs:/app/logs:rw
    environment:
      - FLASK_APP=api_server.py
      - FLASK_ENV=production
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=cadastro_db
      - POSTGRES_USER=cadastro_user
      - POSTGRES_PASSWORD=cadastro_password
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    command: ["python", "api_server.py"]
    restart: unless-stopped
    networks:
      - cadastro-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  cadastro-network:
    driver: bridge 