# Docker Compose para Cadastro Streamlit - Versao Ultra Leve para Raspberry Pi
# Usa PostgreSQL 11 e configuracoes minimas

version: '3.8'

services:
  # Servico PostgreSQL - Versao ultra leve para Raspberry Pi
  postgres:
    image: postgres:11-alpine
    container_name: cadastro_banco
    environment:
      POSTGRES_DB: cadastro_db
      POSTGRES_USER: cadastro_user
      POSTGRES_PASSWORD: cadastro_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
      # Configuracoes ultra leves para Raspberry Pi
      POSTGRES_SHARED_BUFFERS: "64MB"
      POSTGRES_EFFECTIVE_CACHE_SIZE: "128MB"
      POSTGRES_MAINTENANCE_WORK_MEM: "32MB"
      POSTGRES_CHECKPOINT_COMPLETION_TARGET: "0.9"
      POSTGRES_WAL_BUFFERS: "8MB"
      POSTGRES_DEFAULT_STATISTICS_TARGET: "50"
      # Configuracoes de memoria
      POSTGRES_MAX_CONNECTIONS: "20"
      POSTGRES_SHARED_PRELOAD_LIBRARIES: ""
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    restart: unless-stopped
    networks:
      - cadastro-network
    # Configuracoes de recursos para Raspberry Pi
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  cadastro-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadastro_app
    ports:
      - "8503:8501"
    volumes:
      - ./data:/app/data:rw
      - ./config:/app/config:rw
      - ./logs:/app/logs:rw
    environment:
      STREAMLIT_SERVER_PORT: 8501
      STREAMLIT_SERVER_HEADLESS: "true"
      STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
      STREAMLIT_SERVER_ENABLE_CORS: "false"
      STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION: "false"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: cadastro_db
      POSTGRES_USER: cadastro_user
      POSTGRES_PASSWORD: cadastro_password
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    restart: unless-stopped
    networks:
      - cadastro-network
    depends_on:
      - postgres
    # Configuracoes de recursos para Raspberry Pi
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadastro_api
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data:rw
      - ./config:/app/config:rw
      - ./logs:/app/logs:rw
    environment:
      FLASK_APP: api_server.py
      FLASK_ENV: production
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: cadastro_db
      POSTGRES_USER: cadastro_user
      POSTGRES_PASSWORD: cadastro_password
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    command: ["python", "api_server.py"]
    restart: unless-stopped
    networks:
      - cadastro-network
    depends_on:
      - postgres
    # Configuracoes de recursos para Raspberry Pi
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  postgres_data:
    driver: local

networks:
  cadastro-network:
    driver: bridge
