version: '3.8'

services:
  cadastro-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadastro-streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data:rw
      - ./config:/app/config:rw
      - ./logs:/app/logs:rw
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped
    networks:
      - cadastro-network

  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadastro-api
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data:rw
      - ./config:/app/config:rw
      - ./logs:/app/logs:rw
    environment:
      - FLASK_APP=api_server.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    command: ["python", "api_server.py"]
    restart: unless-stopped
    networks:
      - cadastro-network

networks:
  cadastro-network:
    driver: bridge
